from app.models.product import Product
from app.models.search_result import SearchResult

def seed_products(db):
    """
    Начальное заполнение локальной товарной базы.

    В рамках ВКР эти данные рассматриваются как локальная копия
    товарных данных.
    """

    # Сначала удаляем результаты поисков,
    # потому что они ссылаются на товары через внешний ключ
    db.query(SearchResult).delete()
    db.commit()

    # Потом можно удалять старые товары
    db.query(Product).delete()
    db.commit()

    products_data = [
        # БЕНЗОПИЛЫ
        {
            "external_id": "1C-BP-0001",
            "article": "MS180-35",
            "name": "Бензопила Stihl MS 180 2.0 л.с. шина 35 см",
            "category": "бензопила",
            "brand": "stihl",
            "price": 22900,
            "stock": 4,
            "power_type": "gasoline",
            "area_min": 2,
            "area_max": 12,
            "description": "Бензиновая цепная пила для заготовки дров и ухода за участком",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0002",
            "article": "MS181-35",
            "name": "Бензопила Stihl MS 181 C-BE шина 35 см",
            "category": "бензопила",
            "brand": "stihl",
            "price": 31900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 3,
            "area_max": 15,
            "description": "Надёжная бензопила для дачи, сада и заготовки дров",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0003",
            "article": "CH237-16",
            "name": "Бензопила Champion 237-16 2.0 л.с. шина 40 см",
            "category": "бензопила",
            "brand": "champion",
            "price": 10900,
            "stock": 8,
            "power_type": "gasoline",
            "area_min": 2,
            "area_max": 15,
            "description": "Недорогая бензопила для дров, веток и хозяйственных работ",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0004",
            "article": "CH241-16",
            "name": "Бензопила Champion 241-16 для дачи и сада",
            "category": "бензопила",
            "brand": "champion",
            "price": 12900,
            "stock": 5,
            "power_type": "gasoline",
            "area_min": 2,
            "area_max": 16,
            "description": "Бензиновая пила для бытового использования на участке",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0005",
            "article": "HUSQ120",
            "name": "Бензопила Husqvarna 120 Mark II для заготовки дров",
            "category": "бензопила",
            "brand": "husqvarna",
            "price": 24900,
            "stock": 3,
            "power_type": "gasoline",
            "area_min": 3,
            "area_max": 15,
            "description": "Бензопила для дров, веток и обслуживания садового участка",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0006",
            "article": "HUT-BS45",
            "name": "Бензопила Huter BS-45 2.3 л.с. шина 45 см",
            "category": "бензопила",
            "brand": "huter",
            "price": 11900,
            "stock": 6,
            "power_type": "gasoline",
            "area_min": 3,
            "area_max": 18,
            "description": "Мощная бензопила для распила древесины и заготовки дров",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0007",
            "article": "MAK-UC4041A",
            "name": "Электропила Makita UC4041A 1800 Вт шина 40 см",
            "category": "бензопила",
            "brand": "makita",
            "price": 14900,
            "stock": 4,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 8,
            "description": "Электрическая цепная пила для участка рядом с домом",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0008",
            "article": "BOS-AKE40",
            "name": "Электропила Bosch AKE 40 S для веток и дров",
            "category": "бензопила",
            "brand": "bosch",
            "price": 15900,
            "stock": 3,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 8,
            "description": "Электропила для бытовых работ на даче и в саду",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0009",
            "article": "CAR-PSG45",
            "name": "Бензопила Carver PSG-45-15 для хозяйственных работ",
            "category": "бензопила",
            "brand": "carver",
            "price": 9900,
            "stock": 7,
            "power_type": "gasoline",
            "area_min": 2,
            "area_max": 14,
            "description": "Бюджетная бензопила для частного дома и дачи",
            "source": "local",
        },
        {
            "external_id": "1C-BP-0010",
            "article": "ZUBR-PC2545",
            "name": "Бензопила Зубр ПБЦ-2545 для дров и дерева",
            "category": "бензопила",
            "brand": "зубр",
            "price": 13900,
            "stock": 5,
            "power_type": "gasoline",
            "area_min": 3,
            "area_max": 18,
            "description": "Бензопила для заготовки дров и распила древесины",
            "source": "local",
        },

        # ТРИММЕРЫ
        {
            "external_id": "1C-TR-0001",
            "article": "HUT-GGT2500",
            "name": "Триммер бензиновый Huter GGT-2500T для высокой травы",
            "category": "триммер",
            "brand": "huter",
            "price": 12900,
            "stock": 6,
            "power_type": "gasoline",
            "area_min": 6,
            "area_max": 20,
            "description": "Бензиновый триммер для высокой травы и больших участков",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0002",
            "article": "BOS-EGC26",
            "name": "Триммер электрический Bosch EasyGrassCut 26 для газона",
            "category": "триммер",
            "brand": "bosch",
            "price": 6900,
            "stock": 10,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 6,
            "description": "Электрический триммер для небольшого участка рядом с домом",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0003",
            "article": "CH-T433",
            "name": "Триммер Champion T433-2 бензиновый для участка",
            "category": "триммер",
            "brand": "champion",
            "price": 15900,
            "stock": 5,
            "power_type": "gasoline",
            "area_min": 8,
            "area_max": 25,
            "description": "Мощный бензиновый триммер для травы и бурьяна",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0004",
            "article": "PAT-TR340",
            "name": "Триммер аккумуляторный Patriot TR 340XL для дачи",
            "category": "триммер",
            "brand": "patriot",
            "price": 9900,
            "stock": 4,
            "power_type": "battery",
            "area_min": 2,
            "area_max": 8,
            "description": "Аккумуляторный триммер для мобильной работы без провода",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0005",
            "article": "STIHL-FS55",
            "name": "Триммер бензиновый Stihl FS 55 для травы и сорняков",
            "category": "триммер",
            "brand": "stihl",
            "price": 27900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 18,
            "description": "Надёжный бензиновый триммер для садового участка",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0006",
            "article": "MAK-UR3501",
            "name": "Триммер электрический Makita UR3501 для газона",
            "category": "триммер",
            "brand": "makita",
            "price": 11900,
            "stock": 3,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 7,
            "description": "Электрический триммер для ухода за газоном",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0007",
            "article": "CAR-GBC52",
            "name": "Бензокоса Carver GBC-52 для высокой травы",
            "category": "триммер",
            "brand": "carver",
            "price": 8900,
            "stock": 8,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 18,
            "description": "Бюджетная бензокоса для покоса травы на участке",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0008",
            "article": "ZUBR-TB2500",
            "name": "Триммер бензиновый Зубр ТБ-2500 для дачи",
            "category": "триммер",
            "brand": "зубр",
            "price": 13500,
            "stock": 5,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 20,
            "description": "Бензиновый триммер для травы, сорняков и дачного участка",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0009",
            "article": "HUSQ-128R",
            "name": "Триммер Husqvarna 128R бензиновый профессиональный",
            "category": "триммер",
            "brand": "husqvarna",
            "price": 32900,
            "stock": 1,
            "power_type": "gasoline",
            "area_min": 8,
            "area_max": 25,
            "description": "Мощный триммер для интенсивного ухода за участком",
            "source": "local",
        },
        {
            "external_id": "1C-TR-0010",
            "article": "DENZEL-ET1200",
            "name": "Триммер электрический Denzel ET-1200 для небольшого участка",
            "category": "триммер",
            "brand": "denzel",
            "price": 5900,
            "stock": 9,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 5,
            "description": "Недорогой электрический триммер для газона и дачи",
            "source": "local",
        },

        # ГАЗОНОКОСИЛКИ
        {
            "external_id": "1C-GZ-0001",
            "article": "CH-LM4627",
            "name": "Газонокосилка Champion LM4627 бензиновая самоходная",
            "category": "газонокосилка",
            "brand": "champion",
            "price": 32900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 8,
            "area_max": 25,
            "description": "Самоходная газонокосилка для больших газонов",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0002",
            "article": "BOS-ARM37",
            "name": "Газонокосилка Bosch ARM 37 электрическая для газона",
            "category": "газонокосилка",
            "brand": "bosch",
            "price": 18900,
            "stock": 4,
            "power_type": "electric",
            "area_min": 3,
            "area_max": 10,
            "description": "Электрическая газонокосилка для ухода за газоном возле дома",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0003",
            "article": "HUT-GLM4200",
            "name": "Газонокосилка Huter GLM-4200 бензиновая",
            "category": "газонокосилка",
            "brand": "huter",
            "price": 25900,
            "stock": 3,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 18,
            "description": "Бензиновая газонокосилка для дачи и среднего участка",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0004",
            "article": "PAT-PT47LS",
            "name": "Газонокосилка Patriot PT 47 LS бензиновая",
            "category": "газонокосилка",
            "brand": "patriot",
            "price": 29900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 6,
            "area_max": 20,
            "description": "Газонокосилка для ухода за участком и высокой травой",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0005",
            "article": "MAK-ELM3720",
            "name": "Газонокосилка Makita ELM3720 электрическая",
            "category": "газонокосилка",
            "brand": "makita",
            "price": 17900,
            "stock": 5,
            "power_type": "electric",
            "area_min": 2,
            "area_max": 9,
            "description": "Электрическая газонокосилка для небольшого и среднего газона",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0006",
            "article": "ZUBR-GKE400",
            "name": "Газонокосилка Зубр ГКЭ-400 электрическая",
            "category": "газонокосилка",
            "brand": "зубр",
            "price": 13900,
            "stock": 6,
            "power_type": "electric",
            "area_min": 2,
            "area_max": 8,
            "description": "Недорогая электрическая газонокосилка для дачного газона",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0007",
            "article": "DENZEL-GLD520",
            "name": "Газонокосилка Denzel GLD-520 бензиновая",
            "category": "газонокосилка",
            "brand": "denzel",
            "price": 27900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 6,
            "area_max": 18,
            "description": "Бензиновая газонокосилка для среднего участка",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0008",
            "article": "CAR-LMG2646",
            "name": "Газонокосилка Carver LMG-2646 бензиновая",
            "category": "газонокосилка",
            "brand": "carver",
            "price": 23900,
            "stock": 4,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 16,
            "description": "Газонокосилка для ухода за травой на дачном участке",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0009",
            "article": "CH-EM4216",
            "name": "Газонокосилка Champion EM4216 электрическая",
            "category": "газонокосилка",
            "brand": "champion",
            "price": 12900,
            "stock": 7,
            "power_type": "electric",
            "area_min": 2,
            "area_max": 7,
            "description": "Электрическая газонокосилка для небольшого газона",
            "source": "local",
        },
        {
            "external_id": "1C-GZ-0010",
            "article": "HUSQ-LC140",
            "name": "Газонокосилка Husqvarna LC 140 бензиновая",
            "category": "газонокосилка",
            "brand": "husqvarna",
            "price": 42900,
            "stock": 1,
            "power_type": "gasoline",
            "area_min": 6,
            "area_max": 20,
            "description": "Надёжная бензиновая газонокосилка для частного участка",
            "source": "local",
        },

        # КУЛЬТИВАТОРЫ
        {
            "external_id": "1C-KL-0001",
            "article": "HUT-GMC50",
            "name": "Культиватор Huter GMC-5.0 для обработки почвы",
            "category": "культиватор",
            "brand": "huter",
            "price": 27900,
            "stock": 5,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 18,
            "description": "Культиватор для рыхления земли и обработки огорода",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0002",
            "article": "CH-BC5712",
            "name": "Культиватор Champion BC5712 для рыхления земли",
            "category": "культиватор",
            "brand": "champion",
            "price": 31900,
            "stock": 3,
            "power_type": "gasoline",
            "area_min": 8,
            "area_max": 25,
            "description": "Бензиновый культиватор для огорода и обработки почвы",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0003",
            "article": "PAT-T2030",
            "name": "Культиватор Patriot Т 2030 Denver электрический",
            "category": "культиватор",
            "brand": "patriot",
            "price": 11900,
            "stock": 6,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 6,
            "description": "Электрический культиватор для грядок и лёгкой почвы",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0004",
            "article": "ZUBR-MKT1500",
            "name": "Культиватор Зубр МКТ-1500 электрический для грядок",
            "category": "культиватор",
            "brand": "зубр",
            "price": 9900,
            "stock": 8,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 5,
            "description": "Компактный культиватор для небольшого огорода",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0005",
            "article": "CAR-T650R",
            "name": "Культиватор Carver T-650R бензиновый для огорода",
            "category": "культиватор",
            "brand": "carver",
            "price": 24900,
            "stock": 4,
            "power_type": "gasoline",
            "area_min": 4,
            "area_max": 16,
            "description": "Культиватор для рыхления и подготовки земли к посадке",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0006",
            "article": "DENZEL-T500",
            "name": "Культиватор Denzel T-500 бензиновый для почвы",
            "category": "культиватор",
            "brand": "denzel",
            "price": 26900,
            "stock": 3,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 18,
            "description": "Бензиновый культиватор для обработки земли на участке",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0007",
            "article": "CH-EC750",
            "name": "Культиватор Champion EC750 электрический лёгкий",
            "category": "культиватор",
            "brand": "champion",
            "price": 8900,
            "stock": 5,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 4,
            "description": "Лёгкий электрический культиватор для теплицы и грядок",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0008",
            "article": "HUT-GMC70",
            "name": "Культиватор Huter GMC-7.0 мощный для огорода",
            "category": "культиватор",
            "brand": "huter",
            "price": 38900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 8,
            "area_max": 30,
            "description": "Мощный культиватор для плотной почвы и большого участка",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0009",
            "article": "PAT-OREGON",
            "name": "Культиватор Patriot Oregon бензиновый для дачи",
            "category": "культиватор",
            "brand": "patriot",
            "price": 29900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 20,
            "description": "Культиватор для обработки земли на дачном участке",
            "source": "local",
        },
        {
            "external_id": "1C-KL-0010",
            "article": "ZUBR-MKT2000",
            "name": "Культиватор Зубр МКТ-2000 электрический для огорода",
            "category": "культиватор",
            "brand": "зубр",
            "price": 12900,
            "stock": 4,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 7,
            "description": "Электрический культиватор для рыхления земли на грядках",
            "source": "local",
        },

        # МОТОБЛОКИ
        {
            "external_id": "1C-MB-0001",
            "article": "NEVA-MB2",
            "name": "Мотоблок Нева МБ-2 для вспашки земли",
            "category": "мотоблок",
            "brand": "нева",
            "price": 68900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 15,
            "area_max": 50,
            "description": "Мотоблок для огорода, хозяйства и обработки больших участков",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0002",
            "article": "OKA-MB1D",
            "name": "Мотоблок Ока МБ-1Д1М10 для огорода и хозяйства",
            "category": "мотоблок",
            "brand": "ока",
            "price": 55900,
            "stock": 1,
            "power_type": "gasoline",
            "area_min": 10,
            "area_max": 35,
            "description": "Мотоблок для обработки земли и хозяйственных работ",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0003",
            "article": "CH-9714",
            "name": "Мотоблок Champion BC9714 для вспашки участка",
            "category": "мотоблок",
            "brand": "champion",
            "price": 62900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 12,
            "area_max": 45,
            "description": "Мотоблок для вспашки и обработки почвы на участке",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0004",
            "article": "HUT-MK7500",
            "name": "Мотоблок Huter МК-7500 для земли и огорода",
            "category": "мотоблок",
            "brand": "huter",
            "price": 58900,
            "stock": 3,
            "power_type": "gasoline",
            "area_min": 10,
            "area_max": 40,
            "description": "Мотоблок для обработки земли и работ на даче",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0005",
            "article": "PAT-URAL",
            "name": "Мотоблок Patriot Урал бензиновый для хозяйства",
            "category": "мотоблок",
            "brand": "patriot",
            "price": 64900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 12,
            "area_max": 45,
            "description": "Мотоблок для вспашки, обработки почвы и хозяйственных задач",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0006",
            "article": "CAR-MT900",
            "name": "Мотоблок Carver MT-900 бензиновый",
            "category": "мотоблок",
            "brand": "carver",
            "price": 52900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 10,
            "area_max": 35,
            "description": "Мотоблок для огорода, рыхления и перевозки грузов",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0007",
            "article": "DENZEL-DPT950",
            "name": "Мотоблок Denzel DPT-950 для большого участка",
            "category": "мотоблок",
            "brand": "denzel",
            "price": 71900,
            "stock": 1,
            "power_type": "gasoline",
            "area_min": 15,
            "area_max": 55,
            "description": "Мощный мотоблок для большого участка и хозяйственных работ",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0008",
            "article": "ZUBR-MT65",
            "name": "Мотоблок Зубр МТБ-650 для обработки почвы",
            "category": "мотоблок",
            "brand": "зубр",
            "price": 59900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 10,
            "area_max": 40,
            "description": "Мотоблок для обработки земли, огорода и хозяйства",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0009",
            "article": "CH-1193",
            "name": "Мотоблок Champion DC1193E дизельный для хозяйства",
            "category": "мотоблок",
            "brand": "champion",
            "price": 89900,
            "stock": 1,
            "power_type": "gasoline",
            "area_min": 20,
            "area_max": 70,
            "description": "Тяжёлый мотоблок для большого участка и интенсивных работ",
            "source": "local",
        },
        {
            "external_id": "1C-MB-0010",
            "article": "NEVA-MB23",
            "name": "Мотоблок Нева МБ-23 мощный для вспашки",
            "category": "мотоблок",
            "brand": "нева",
            "price": 84900,
            "stock": 1,
            "power_type": "gasoline",
            "area_min": 20,
            "area_max": 70,
            "description": "Мощный мотоблок для плотной почвы и больших площадей",
            "source": "local",
        },

        # НАСОСЫ
        {
            "external_id": "1C-NS-0001",
            "article": "ZUBR-NPG400",
            "name": "Насос дренажный Зубр НПГ-М1-400 для воды и полива",
            "category": "насос",
            "brand": "зубр",
            "price": 4500,
            "stock": 9,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 10,
            "description": "Насос для воды, полива и откачки с участка",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0002",
            "article": "PAT-F900",
            "name": "Насос Patriot F 900 для колодца и полива участка",
            "category": "насос",
            "brand": "patriot",
            "price": 7900,
            "stock": 4,
            "power_type": "electric",
            "area_min": 5,
            "area_max": 20,
            "description": "Насос для полива участка и работы с водой из колодца",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0003",
            "article": "ZUBR-NPCH1000",
            "name": "Насос скважинный Зубр НПЧ-Т5-1000 для скважины",
            "category": "насос",
            "brand": "зубр",
            "price": 11900,
            "stock": 0,
            "power_type": "electric",
            "area_min": 5,
            "area_max": 25,
            "description": "Скважинный насос для водоснабжения и полива",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0004",
            "article": "CH-GP600",
            "name": "Насос Champion GP600 для полива сада",
            "category": "насос",
            "brand": "champion",
            "price": 6900,
            "stock": 7,
            "power_type": "electric",
            "area_min": 3,
            "area_max": 15,
            "description": "Поверхностный насос для полива сада и огорода",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0005",
            "article": "HUT-MP50",
            "name": "Насос Huter MP-50 бензиновый для откачки воды",
            "category": "насос",
            "brand": "huter",
            "price": 14900,
            "stock": 3,
            "power_type": "gasoline",
            "area_min": 5,
            "area_max": 30,
            "description": "Мотопомпа для откачки воды и полива большого участка",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0006",
            "article": "DENZEL-DP400",
            "name": "Насос дренажный Denzel DP400 для грязной воды",
            "category": "насос",
            "brand": "denzel",
            "price": 3900,
            "stock": 10,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 10,
            "description": "Дренажный насос для откачки воды на участке",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0007",
            "article": "CAR-GP800",
            "name": "Насос Carver GP-800 для колодца и полива",
            "category": "насос",
            "brand": "carver",
            "price": 8500,
            "stock": 4,
            "power_type": "electric",
            "area_min": 4,
            "area_max": 18,
            "description": "Насос для полива участка и подачи воды из колодца",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0008",
            "article": "PAT-VP10",
            "name": "Насос вибрационный Patriot VP-10 для колодца",
            "category": "насос",
            "brand": "patriot",
            "price": 2900,
            "stock": 12,
            "power_type": "electric",
            "area_min": 1,
            "area_max": 8,
            "description": "Недорогой насос для колодца и бытового полива",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0009",
            "article": "ZUBR-NAS800",
            "name": "Насосная станция Зубр НС-Т3-800 для дома и дачи",
            "category": "насос",
            "brand": "зубр",
            "price": 13900,
            "stock": 3,
            "power_type": "electric",
            "area_min": 5,
            "area_max": 25,
            "description": "Насосная станция для дома, дачи и водоснабжения",
            "source": "local",
        },
        {
            "external_id": "1C-NS-0010",
            "article": "CH-MP80",
            "name": "Мотопомпа Champion GP80 бензиновая для воды",
            "category": "насос",
            "brand": "champion",
            "price": 18900,
            "stock": 2,
            "power_type": "gasoline",
            "area_min": 8,
            "area_max": 35,
            "description": "Бензиновая мотопомпа для перекачки воды и полива",
            "source": "local",
        },

        # ОПРЫСКИВАТЕЛИ
        {
            "external_id": "1C-OP-0001",
            "article": "ZHUK-10L",
            "name": "Опрыскиватель садовый Жук 10 л для обработки растений",
            "category": "опрыскиватель",
            "brand": "жук",
            "price": 1900,
            "stock": 20,
            "power_type": "manual",
            "area_min": 1,
            "area_max": 5,
            "description": "Ручной опрыскиватель для сада, растений и теплицы",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0002",
            "article": "PAT-PT16AC",
            "name": "Опрыскиватель Patriot PT-16AC аккумуляторный для сада",
            "category": "опрыскиватель",
            "brand": "patriot",
            "price": 4900,
            "stock": 7,
            "power_type": "battery",
            "area_min": 3,
            "area_max": 12,
            "description": "Аккумуляторный опрыскиватель для удобной обработки сада",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0003",
            "article": "ZUBR-12L",
            "name": "Опрыскиватель Зубр 12 л ручной для растений",
            "category": "опрыскиватель",
            "brand": "зубр",
            "price": 2200,
            "stock": 15,
            "power_type": "manual",
            "area_min": 1,
            "area_max": 6,
            "description": "Ручной садовый опрыскиватель для кустов и деревьев",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0004",
            "article": "CH-SA16",
            "name": "Опрыскиватель Champion SA16 аккумуляторный",
            "category": "опрыскиватель",
            "brand": "champion",
            "price": 5900,
            "stock": 5,
            "power_type": "battery",
            "area_min": 3,
            "area_max": 15,
            "description": "Аккумуляторный опрыскиватель для сада и участка",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0005",
            "article": "HUT-SPR16",
            "name": "Опрыскиватель Huter SP-16AC аккумуляторный",
            "category": "опрыскиватель",
            "brand": "huter",
            "price": 5400,
            "stock": 6,
            "power_type": "battery",
            "area_min": 3,
            "area_max": 15,
            "description": "Опрыскиватель для обработки сада, деревьев и растений",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0006",
            "article": "DENZEL-8L",
            "name": "Опрыскиватель Denzel 8 л ручной для теплицы",
            "category": "опрыскиватель",
            "brand": "denzel",
            "price": 1600,
            "stock": 18,
            "power_type": "manual",
            "area_min": 1,
            "area_max": 4,
            "description": "Ручной опрыскиватель для теплицы и небольшого сада",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0007",
            "article": "CAR-AS16",
            "name": "Опрыскиватель Carver AS-16 аккумуляторный для дачи",
            "category": "опрыскиватель",
            "brand": "carver",
            "price": 4700,
            "stock": 4,
            "power_type": "battery",
            "area_min": 2,
            "area_max": 12,
            "description": "Аккумуляторный опрыскиватель для ухода за дачным участком",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0008",
            "article": "ZHUK-5L",
            "name": "Опрыскиватель Жук 5 л ручной для растений",
            "category": "опрыскиватель",
            "brand": "жук",
            "price": 1100,
            "stock": 25,
            "power_type": "manual",
            "area_min": 1,
            "area_max": 3,
            "description": "Компактный ручной опрыскиватель для цветов и растений",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0009",
            "article": "PAT-PT12",
            "name": "Опрыскиватель Patriot PT-12 ручной садовый",
            "category": "опрыскиватель",
            "brand": "patriot",
            "price": 2100,
            "stock": 12,
            "power_type": "manual",
            "area_min": 1,
            "area_max": 6,
            "description": "Ручной опрыскиватель для обработки растений и кустов",
            "source": "local",
        },
        {
            "external_id": "1C-OP-0010",
            "article": "ZUBR-AO16",
            "name": "Опрыскиватель Зубр АО-16 аккумуляторный для сада",
            "category": "опрыскиватель",
            "brand": "зубр",
            "price": 6200,
            "stock": 3,
            "power_type": "battery",
            "area_min": 3,
            "area_max": 15,
            "description": "Аккумуляторный опрыскиватель для большого сада и участка",
            "source": "local",
        },
    ]

    products = [Product(**item) for item in products_data]

    db.add_all(products)
    db.commit()

    print(f"Товары успешно обновлены. Загружено позиций: {len(products)}")